In [53]:
import pandas as pd

CSV_FILE = "../input_files/individual_repo_collection.csv"
df = pd.read_csv(CSV_FILE)

In [54]:
df["Owner account Name"] = "Individual"

In [55]:
df.head()

,Owner account Name,Repo Name,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking
0,Individual,SikumAI,https://github.com/buzagloidan/SikumAI,False,5/19/25 14:21,7/12/25 18:13,7/12/25 18:13,git://github.com/buzagloidan/SikumAI.git,3123,10,10,TypeScript,1,False,False,0,MIT License,True
1,Individual,laughing-octo-fiesta,https://github.com/Lyttell/laughing-octo-fiesta,False,10/16/21 20:26,11/11/24 4:59,2/9/22 9:26,git://github.com/Lyttell/laughing-octo-fiesta.git,1221,9,9,TypeScript,1,False,False,1,NaN,True
2,Individual,verify-hcaptcha,https://github.com/velut/verify-hcaptcha,False,9/30/21 21:02,8/7/25 19:09,8/7/25 19:09,git://github.com/velut/verify-hcaptcha.git,1724,8,8,TypeScript,0,False,False,0,MIT License,True
3,Individual,skincare-routine-builder,https://github.com/matija2209/skincare-routine...,False,1/30/25 14:48,7/9/25 21:29,3/7/25 15:04,git://github.com/matija2209/skincare-routine-b...,254,8,8,TypeScript,2,False,False,1,NaN,True
4,Individual,discord-quests-bot,https://github.com/7xrrr/discord-quests-bot,False,3/29/25 19:27,7/24/25 20:14,7/24/25 20:14,git://github.com/7xrrr/discord-quests-bot.git,2218,7,7,TypeScript,9,False,False,0,GNU General Public License v3.0,True

In [56]:
df = df.drop('Repo Name', axis=1)

In [57]:
df = df.rename(columns={'Owner account Name': 'Organization'})

In [58]:
df.head()

,Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking
0,Individual,https://github.com/buzagloidan/SikumAI,False,5/19/25 14:21,7/12/25 18:13,7/12/25 18:13,git://github.com/buzagloidan/SikumAI.git,3123,10,10,TypeScript,1,False,False,0,MIT License,True
1,Individual,https://github.com/Lyttell/laughing-octo-fiesta,False,10/16/21 20:26,11/11/24 4:59,2/9/22 9:26,git://github.com/Lyttell/laughing-octo-fiesta.git,1221,9,9,TypeScript,1,False,False,1,NaN,True
2,Individual,https://github.com/velut/verify-hcaptcha,False,9/30/21 21:02,8/7/25 19:09,8/7/25 19:09,git://github.com/velut/verify-hcaptcha.git,1724,8,8,TypeScript,0,False,False,0,MIT License,True
3,Individual,https://github.com/matija2209/skincare-routine...,False,1/30/25 14:48,7/9/25 21:29,3/7/25 15:04,git://github.com/matija2209/skincare-routine-b...,254,8,8,TypeScript,2,False,False,1,NaN,True
4,Individual,https://github.com/7xrrr/discord-quests-bot,False,3/29/25 19:27,7/24/25 20:14,7/24/25 20:14,git://github.com/7xrrr/discord-quests-bot.git,2218,7,7,TypeScript,9,False,False,0,GNU General Public License v3.0,True

In [59]:
# Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking

In [60]:
print(df.columns)

Index(['Organization', 'html_url', 'fork', 'created_at', 'updated_at',
       'pushed_at', 'git_url', 'size', 'stargazers_count', 'watchers_count',
       'language', 'forks_count', 'archived', 'disabled', 'open_issues_count',
       'license', 'allow_forking'],
      dtype='object')

In [61]:
df.to_csv("../input_files/individual_repos.csv", index= False)

In [62]:
import pandas as pd

CSV_FILE = "../input_files/ngo_foundations_repos.csv"
df = pd.read_csv(CSV_FILE)

In [63]:
df["project_type"] = 2

In [64]:
df.head()

,Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking,project_type
0,Apache,https://github.com/apache/tapestry3,False,2009-03-27T15:41:52Z,2025-04-14T03:46:39Z,2024-12-08T15:49:38Z,git://github.com/apache/tapestry3.git,54950,5,5,Java,11,True,False,7,NaN,True,2
1,Apache,https://github.com/apache/apr-iconv,False,2009-03-27T15:41:52Z,2025-06-03T03:02:22Z,2019-01-01T11:45:15Z,git://github.com/apache/apr-iconv.git,2539,22,22,C,18,False,False,1,Apache License 2.0,True,2
2,Apache,https://github.com/apache/tapestry4,False,2009-03-27T15:41:53Z,2025-06-19T19:37:14Z,2024-12-08T15:51:22Z,git://github.com/apache/tapestry4.git,76627,7,7,Java,12,True,False,12,Other,True,2
3,Apache,https://github.com/apache/xalan-j,False,2009-03-27T15:41:55Z,2025-07-02T10:13:48Z,2022-10-24T18:27:46Z,git://github.com/apache/xalan-j.git,55092,23,23,Java,64,False,False,4,Other,True,2
4,Apache,https://github.com/apache/etch,False,2009-03-27T15:41:55Z,2022-11-28T16:04:48Z,2017-04-28T20:27:41Z,git://github.com/apache/etch.git,13740,17,17,Java,8,False,False,0,Apache License 2.0,True,2

In [65]:
print(df.columns)

Index(['Organization', 'html_url', 'fork', 'created_at', 'updated_at',
       'pushed_at', 'git_url', 'size', 'stargazers_count', 'watchers_count',
       'language', 'forks_count', 'archived', 'disabled', 'open_issues_count',
       'license', 'allow_forking', 'project_type'],
      dtype='object')

In [66]:
import pandas as pd

CSV_FILE1 = "../input_files/repo_collections_list.csv"

df1 = pd.read_csv(CSV_FILE1)

df1["project_type"] = 1

######

CSV_FILE2 = "../input_files/ngo_foundations_repos.csv"

df2 = pd.read_csv(CSV_FILE2)

df2["project_type"] = 2

######

CSV_FILE3 = "../input_files/individual_repos.csv"

df3 = pd.read_csv(CSV_FILE3)

df3["project_type"] = 3

In [67]:
df_combined = pd.concat([df1, df2, df3], ignore_index=True)
#print(df_combined)

In [68]:
df_combined.head()

,Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking,project_type
0,Microsoft,https://github.com/microsoft/HealthVault-Mobil...,False,2011-06-21T22:49:39Z,2024-09-14T17:51:15Z,2017-04-28T17:05:02Z,git://github.com/microsoft/HealthVault-Mobile-...,798,42,42,Objective-C,21,True,False,2,NaN,True,1
1,Microsoft,https://github.com/microsoft/BeanSpy,False,2012-01-02T02:03:37Z,2024-09-21T22:23:08Z,2022-09-22T15:27:15Z,git://github.com/microsoft/BeanSpy.git,226,23,23,Java,18,True,False,5,Other,True,1
2,Microsoft,https://github.com/microsoft/healthvault-ios-sdk,False,2012-04-17T01:33:37Z,2024-11-07T22:34:43Z,2017-10-10T17:03:00Z,git://github.com/microsoft/healthvault-ios-sdk...,10007,26,26,C,15,True,False,2,Other,True,1
3,Microsoft,https://github.com/microsoft/WindowsAzureToolk...,False,2012-08-28T18:33:11Z,2023-01-28T10:54:02Z,2016-03-15T20:13:51Z,git://github.com/microsoft/WindowsAzureToolkit...,82855,42,42,Java,38,True,False,2,NaN,True,1
4,Microsoft,https://github.com/microsoft/php-sdk-binary-tools,False,2013-05-15T09:42:29Z,2025-02-26T15:44:23Z,2022-01-10T03:47:21Z,git://github.com/microsoft/php-sdk-binary-tool...,116066,271,271,M4,80,True,False,2,"BSD 2-Clause ""Simplified"" License",True,1

In [69]:
df_combined.to_csv("../input_files/enterprise_ngo_foundation_individual_repos_combined.csv", index= False)