In [1]:
# TABLE: repo_collection

import psycopg2
import pandas as pd
from db_operations import get_db_conn

# CSV file path
CSV_FILE = "../input_files/repo_collections_list.csv"  # Update with actual file path

try:
    conn = get_db_conn()
    cur = conn.cursor()

    # Read CSV file
    df = pd.read_csv(CSV_FILE)  # Assuming tab-separated file
    df.columns = df.columns.str.strip()

    # Rename columns to match the table
    df.rename(columns={
        "Organization": "organization",
        "html_url": "html_url",
        "fork": "fork",
        "created_at": "created_at",
        "updated_at": "updated_at",
        "pushed_at": "pushed_at",
        "git_url": "git_url",
        "size": "size",
        "stargazers_count": "stargazers_count",
        "watchers_count": "watchers_count",
        "language": "language",
        "forks_count": "forks_count",
        "archived": "archived",
        "disabled": "disabled",
        "open_issues_count": "open_issues_count",
        "license": "license",
        "allow_forking": "allow_forking"
    }, inplace=True)

    # Replace NaN with None for PostgreSQL compatibility
    df = df.where(pd.notna(df), None)

    # Insert data
    for _, row in df.iterrows():
        cur.execute("""
            INSERT INTO repo_collection (
                organization, html_url, fork, created_at, updated_at, pushed_at,
                git_url, size, stargazers_count, watchers_count, language,
                forks_count, archived, disabled, open_issues_count, license, allow_forking
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
        """, (
            row["organization"], row["html_url"], row["fork"], row["created_at"],
            row["updated_at"], row["pushed_at"], row["git_url"], row["size"],
            row["stargazers_count"], row["watchers_count"], row["language"],
            row["forks_count"], row["archived"], row["disabled"],
            row["open_issues_count"], row["license"], row["allow_forking"]
        ))

    # Commit and close
    conn.commit()
    print("Data inserted successfully.")

except Exception as e:
    print("Error:", e)

finally:
    if conn:
        cur.close()
        conn.close()

Data inserted successfully.

In [ ]:
# TABLE: searchrepos

import os
import psycopg2
import pandas as pd
from datetime import datetime
from uuid import uuid4
from db_operations import get_db_conn

# CSV file path
CSV_FILE = "../input_files/repo_collections_list.csv"

try:
    # Connect to PostgreSQL
    conn = get_db_conn()
    cur = conn.cursor()

    # OPTIONAL: Empty the table before inserting data
    cur.execute("TRUNCATE TABLE searchrepos RESTART IDENTITY CASCADE;")
    conn.commit()
    print("Table cleared.")

    # Read CSV file
    df = pd.read_csv(CSV_FILE)

    # Clean column names
    df.columns = df.columns.str.strip()

    # Rename columns to match the database
    df.rename(columns={
        "Organization": "organization",
        "html_url": "repository_url",
        "license": "license",
        "language": "language",
    }, inplace=True)

    # Extract project_id from repository_url (you can customize this logic)
    df["project_id"] = df["repository_url"].apply(lambda x: x.strip('/').split('/')[-1] if pd.notna(x) else "unknown")

    # Generate unique _id
    df["_id"] = df.apply(lambda row: f"{datetime.now().strftime('%Y%m%d%H%M%S%f')}_{uuid4().hex[:6]}", axis=1)

    # Fill missing values
    df["project_version"] = "" 
    df["same_license"] = 0
    df["dif_license_comply"] = 0
    df["license_conflicts"] = 0
    df["high_risks"] = 0
    df["undetermined"] = 0
    df["no_match"] = 0
    df["has_picked"] = False
    df["is_active"] = True
    df["processing_start_time"] = None
    df["processing_end_time"] = None
    df["project_type"] = 0
    

    # Replace NaNs with None
    df = df.where(pd.notna(df), None)

    # Insert data
    for _, row in df.iterrows():
        cur.execute("""
            INSERT INTO searchrepos (
                _id, organization, project_id, project_version, repository_url, license, language,
                same_license, dif_license_comply, license_conflicts, high_risks, undetermined, no_match,
                has_picked, is_active, processing_start_time, processing_end_time
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (_id) DO NOTHING;
        """, (
            row["_id"], row["organization"], row["project_id"], row["project_version"],
            row["repository_url"], row["license"], row["language"],
            row["same_license"], row["dif_license_comply"], row["license_conflicts"],
            row["high_risks"], row["undetermined"], row["no_match"],
            row["has_picked"], row["is_active"], row["processing_start_time"], row["processing_end_time"]
        ))
        
    conn.commit()
    print("✅ Data inserted successfully.")

except Exception as e:
    print("❌ Error:", e)

finally:
    if conn:
        cur.close()
        conn.close()

Table cleared.
✅ Data inserted successfully.

In [1]:
import pandas as pd

CSV_FILE = "../input_files/individual_repo_collection.csv"
df = pd.read_csv(CSV_FILE)

In [3]:
df["Owner account Name"] = "Individual"

In [4]:
df.head()

,Owner account Name,Repo Name,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking
0,Individual,ShareX,https://github.com/ShareX/ShareX,False,2013-10-08T23:32:10Z,2025-08-15T04:24:16Z,2025-08-15T03:26:38Z,git://github.com/ShareX/ShareX.git,63213,33316,33316,C#,3439,False,False,515,GNU General Public License v3.0,True
1,Individual,proxychains,https://github.com/haad/proxychains,False,2011-02-25T12:27:05Z,2025-08-14T09:29:56Z,2024-06-08T02:20:54Z,git://github.com/haad/proxychains.git,538,7368,7368,C,661,False,False,16,GNU General Public License v2.0,True
2,Individual,GQL,https://github.com/AmrDeveloper/GQL,False,2023-06-05T17:46:51Z,2025-08-14T20:22:57Z,2025-08-08T19:30:06Z,git://github.com/AmrDeveloper/GQL.git,7235,3437,3437,Rust,95,False,False,10,MIT License,True
3,Individual,STC,https://github.com/stclib/STC,False,2020-03-03T21:31:51Z,2025-08-14T14:51:36Z,2025-08-13T17:17:28Z,git://github.com/stclib/STC.git,10587,1704,1704,C,98,False,False,5,MIT License,True
4,Individual,pfr,https://github.com/boostorg/pfr,False,2016-03-22T19:26:49Z,2025-08-14T11:44:38Z,2025-08-14T01:24:51Z,git://github.com/boostorg/pfr.git,1317,1416,1416,C++,164,False,False,48,Boost Software License 1.0,True

In [ ]:
df = df.drop('Repo Name', axis=1)

In [7]:
df = df.rename(columns={'Owner account Name': 'Organization'})

In [8]:
df.head()

,Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking
0,Individual,https://github.com/ShareX/ShareX,False,2013-10-08T23:32:10Z,2025-08-15T04:24:16Z,2025-08-15T03:26:38Z,git://github.com/ShareX/ShareX.git,63213,33316,33316,C#,3439,False,False,515,GNU General Public License v3.0,True
1,Individual,https://github.com/haad/proxychains,False,2011-02-25T12:27:05Z,2025-08-14T09:29:56Z,2024-06-08T02:20:54Z,git://github.com/haad/proxychains.git,538,7368,7368,C,661,False,False,16,GNU General Public License v2.0,True
2,Individual,https://github.com/AmrDeveloper/GQL,False,2023-06-05T17:46:51Z,2025-08-14T20:22:57Z,2025-08-08T19:30:06Z,git://github.com/AmrDeveloper/GQL.git,7235,3437,3437,Rust,95,False,False,10,MIT License,True
3,Individual,https://github.com/stclib/STC,False,2020-03-03T21:31:51Z,2025-08-14T14:51:36Z,2025-08-13T17:17:28Z,git://github.com/stclib/STC.git,10587,1704,1704,C,98,False,False,5,MIT License,True
4,Individual,https://github.com/boostorg/pfr,False,2016-03-22T19:26:49Z,2025-08-14T11:44:38Z,2025-08-14T01:24:51Z,git://github.com/boostorg/pfr.git,1317,1416,1416,C++,164,False,False,48,Boost Software License 1.0,True

In [ ]:
# Organization,html_url,fork,created_at,updated_at,pushed_at,git_url,size,stargazers_count,watchers_count,language,forks_count,archived,disabled,open_issues_count,license,allow_forking

In [9]:
print(df.columns)

Index(['Organization', 'html_url', 'fork', 'created_at', 'updated_at',
       'pushed_at', 'git_url', 'size', 'stargazers_count', 'watchers_count',
       'language', 'forks_count', 'archived', 'disabled', 'open_issues_count',
       'license', 'allow_forking'],
      dtype='object')

In [ ]:
df.to_csv("individual_repo_collection_")